// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int reps = Integer.parseInt(args[0]);
		int count = 0;
		double overHalf = 0.0;
		double underHalf = 0.0;
		
		
		while (count < reps) {
			 double r = Math.random();
		
			if ( r > 0.5){
				overHalf++;}
				else { 
					underHalf++;
				}
				count++;
			}
		

		System.out.println("> 0.5: " + (int)overHalf);
		System.out.println("<= 0.5: " + (int)underHalf);

		double ratio =  (overHalf) /  (underHalf);

		if (underHalf == 0.0 || overHalf == 0.0) {
			System.out.println("Ratio is zero, cannot compute ratio.");
		}
			else {
				System.out.println("Ratio: " + ratio);
			 }
		
		
		

}
}
